pull_request_rules:
  - name: approve dependabot pull requests
    conditions:
      - author=dependabot[bot]
    actions:
      review:
        type: APPROVE

  # For Dockerfile updates, trigger codebuild, merge on codebuild status
  - name: write issue comment to start codebuild job
    conditions:
      - author=dependabot[bot]
      - files=Dockerfile
      - "#approved-reviews-by>=1"
    actions:
      comment:
        message: go codebuild go

  - name: merge tardigrade-ci updates
    conditions:
      - author=dependabot[bot]
      - files=Dockerfile
      - status-success=codebuild/default/pr
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge

  # For regular dependabot pr, automatically merge on approve
  - name: merge dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - "#approved-reviews-by>=1"
      - files!=Dockerfile
    actions:
      merge:
        method: merge
